---
title: "AMS 394: Homework #2"
author: "Hivansh Dhakne"
date: "2023-09-25"
---

# Problem 1

## (a)
```{r}
p <- 1 - pnorm(3)
p
```
## (b)
```{r}
p <- 1 - pnorm(42, mean = 35, sd = 6)
p
```
## (c)
```{r}
p <- dbinom(10, size = 10, prob = 0.8)
p
```
## (d)
```{r}
p_d <- punif(0.9)
p_d
```
## (e)
```{r}
p <- 1 - pchisq(6.5, df = 2)
p
```


# Problem 2

## (a)
```{r}
p_outside <- 1 - pnorm(1.96) - pnorm(-1.96)
p_outside
```
## (b)
```{r}
limits <- qnorm(0.01, 0.005, 0.001)
limits
```
## (c)
```{r}
z_scores <- qnorm(0.25, 0.5, 0.75)
z_scores
```

# Problem 3
```{r}
p_comp <- 0.2
p_success <- dbinom(0, size = 10, prob = 1 - p_comp)
p_success
```

#Problem 4

## (a)
```{r}
random_int <- sample(1:80, 15, replace = TRUE)
random_int
```
## (b)
```{r}
random_int <- rmultinom(10, size = 1, prob = c(0.2, 0.3, 0.5))
random_int
```
## (C)
```{r}
random_var <- rexp(10, rate = 3)
random_var
```

# Problem 5
```{r}
coin_toss <- rbinom(10, 1, 0.5)
coin_toss
```

# Problem 6
```{r}
random_v <- runif(1000)
X <- -1/2 * log(1 - random_v) + 1
X
```


# Problem 7

## (a)
## F⁻¹(x) = 
    0,if x < 0.1
    1,if 0.1 ≤ x < 0.3
    2,if 0.3 ≤ x < 0.5
    3,if 0.5 ≤ x < 0.7
    4 everything else
## (b)
```{r}
a <- runif(1000)
x <- ifelse(a < 0.1, 0, ifelse(a < 0.3, 1, ifelse(a < 0.5, 2, ifelse(a < 0.7, 3, 4))))
x
```
## (c)
```{r}
X <- sample(0:4, 1000, replace = TRUE, prob = c(0.1, 0.2, 0.2, 0.2, 0.3))
X
```

# Problem 8
```{r}
chi_5 <- rchisq(1000, 5)
chi_10 <- rchisq(1000, 10)
F_ratio <- chi_5 / chi_10
F_ratio
```

# Problem 9

## (a)
```{r}
p1 <- 0.75
p2 <- 1 - p1

x <- rbinom(1000, 1, p1) * rnorm(1000, 0, 1) + (1 - rbinom(1000, 1, p1)) * 
  rnorm(1000, 3, 1)
x
```
## (b)
```{r}
n <- 1000
p1 <- 0.75
p2 <- 1 - p1

p <- sample(c(0, 3), size = n, replace = TRUE, prob = c(p1, p2))
s <- rnorm(n, mean = p, sd = 1)
s
```

# Problem 10
```{r}
b <- 2
r <- 4
l <- rgamma(1000, shape = r, rate = b)
y <- rexp(1000, rate = l)
y
```


