---
title: "AMS 394: Homework #1"
author: "Hivansh Dhakne"
date: "9/11/2023"
output: pdf_document
---

# Problem 1
## (a)
```{r}
vector_a <- 1:20
vector_a
```
## (b)
```{r}
vector_b <- 20:2
vector_b
```
## (c)
```{r}
vector_c <- c(1:20, 19:1)
vector_c
```
## (d)
```{r}
tmp1 <- c(a = 1, b = 2, c = 3)
tmp1
```
## (e)
```{r}
vector_e <- rep(c(4, 6, 3), times = 10)
vector_e
```
## (f) 
```{r}
vector_f <- c(rep(4, 10), rep(6, 20), rep(3, 30))
tmp2 <- vector_f
tmp2
```


# Problem 2
```{r}
weight <- c(60, 72, 57, 90, 95, 72)
height <- c(1.75, 1.80, 1.65, 1.90, 1.74, 1.91)
```
## (a)
```{r}
num_h_ <- sum(height <= 1.75)
num_h_
```
## (b)
```{r}
indices_h <- which(height <= 1.75)
indices_h
```
## (c)
```{r}
element <- weight[c(2, 3, 5)]
element
```
## (d)
```{r}
sorted <- sort(height)
sorted
```
## (e)
```{r}
ranks <- sort(height)
ranks
```
## (f)
```{r}
combined <- rbind(weight = weight, height = height)
combined
```
## (g)
```{r}
data_list <- list(weight = weight, height = height)
extracted_h <- data_list$height
extracted_h
```

# Problem 3
```{r}
set.seed(123)
tmp <- matrix(sample(10, size = 60, replace = TRUE), nrow = 6)
tmp
```

## (a)
```{r}
prod_4th_col <- prod(tmp[, 4])
prod_4th_col
```
## (b)
```{r}
entries_greater4 <- apply(tmp, 1, function(row) sum(row > 4))
entries_greater4
```
## (c)
```{r}
elements_less3 <- tmp[2, which(tmp[2] < 3)]
elements_less3
```
## (d)
```{r}
element_transpose <- tmp[1, 3]
element_transpose
```

# Problem 4
```{r}
library(ISwR)
data("thuesen")
```
## (a)
```{r}
data_subset <- thuesen[thuesen$blood.glucose > 10 & thuesen$short.velocity > 1.5, ]
data_subset
```
## (b)
```{r}
standard_dev <- sapply(data_subset, sd)
standard_dev
```

# Problem 5
```{r}
tmpFn <- function(x) {
  y <- c()
  for (i in 1:length(x)) {
    y[i] <- x[i]^i
  }
  return(y)
}
```
## example
```{r}
e <- c(5, 10, 15)
tmpFn(e)
```




